# Needed to k8s module
- name: Installing pip
  apt:
    name: python-pip
    state: latest

- name: Updating pip
  pip:
    name: pip
    extra_args: --upgrade
    state: latest
  run_once: true

- name: Installing k8s module dependencies
  pip:
    name: 
      - openshift
      - PyYAML
    state: forcereinstall
  register: install_dependencies

- name: Copy app v1 and v2 deployment file
  template:
    src: "{{ item.value }}.j2"
    dest: "{{ giropops_folder }}/{{ item.value }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ deployment_files | dict2items }}"
  register: copy_app_deploy

- name: App v2 deploy and v1 scale down
  k8s:
    namespace: default
    src: "{{ giropops_folder }}/{{ item.value }}"
    state: present
  with_items: "{{ deployment_files | dict2items }}"

- name: Wait 2 minutes
  pause:
    prompt: App-v1 will be removed in the next 2 minutes. Press Ctrl+c to cancel
    minutes: 2

- name: Remove app-v1
  k8s:
    namespace: default
    state: absent
    src: "{{ giropops_folder }}/{{ deployment_files.v1 }}"
