- name:
  debug:
    msg: "[WORKER] K8S_JOIN_HOLDER - The token is {{ hostvars['K8S_JOIN_HOLDER']['join_command'] }}"
    verbosity: 2

- name: Removing cluster
  command:
    kubeadm reset --force
  register: kubeadm_reset

- name: Adding worker to k8s cluster
  shell: "{{ hostvars['K8S_JOIN_HOLDER']['join_command'] }}"
