- name: Removing old cluster
  command:
    kubeadm reset --force
  register: kubeadm_reset

- name: Initializing k8s cluster
  command:
    kubeadm init
  register: kubeadm_init

- name: Create .kube folder
  file:
    path: ~/.kube
    state: directory

- name: Link admin.conf file to kube folder -> ~/.kube/config
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link

- name: Configuring pod network weavenet
  shell: "kubectl apply -f {{ weavenet_default_url }}"
  register: weavenet_result

- name: Get join command from master
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Adding join command into a dummy host
  add_host:
    name: "K8S_JOIN_HOLDER"
    join_command: "{{ join_command.stdout_lines[0] }}"

- name:
  debug:
    msg: "[MASTER] K8S_JOIN_HOLDER - Join command {{ hostvars['K8S_JOIN_HOLDER']['join_command'] }}"
    verbosity: 2

