- name: Creating giropops application directory
  file: path={{ item.value }} state=directory
  with_items:
    - { value: "{{ giropops_folder }}" }
    - { value: "{{ giropops_folder }}/logs" }
    - { value: "{{ giropops_folder }}/conf" }
  register: create_folder 

- name: Copying app deploy and service files to host
  template: 
    src: "{{ item.filename }}.j2"
    dest: "{{ giropops_folder }}/{{ item.filename }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ deployment_files }}"
  register: copy_template

- name: Creating giropops app deploy and service
  shell: "kubectl apply -f  {{ giropops_folder }}/{{ item.filename }}"
  with_items: "{{ deployment_files }}"
  register: app_deploy
